/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EvaluacionNro3;

import EvaluacionNro2.*;

/**
 *
 * @author Usuario
 */
public class Portada extends javax.swing.JPanel {

    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        titulo = new javax.swing.JPanel();
        materia = new javax.swing.JLabel();
        universidad = new javax.swing.JLabel();
        presentacion = new javax.swing.JPanel();
        alumno = new javax.swing.JLabel();
        profesor = new javax.swing.JLabel();
        imagen = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        titulo.setForeground(new java.awt.Color(240, 240, 240));
        titulo.setOpaque(false);
        titulo.setLayout(new java.awt.GridBagLayout());

        materia.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        materia.setText("Algoritmos y Estructuras I");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BASELINE;
        titulo.add(materia, gridBagConstraints);

        universidad.setFont(new java.awt.Font("Brush Script MT", 3, 36)); // NOI18N
        universidad.setText("Universidad José Antonio Paez");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        titulo.add(universidad, gridBagConstraints);

        add(titulo, java.awt.BorderLayout.PAGE_START);

        presentacion.setForeground(new java.awt.Color(240, 240, 240));
        presentacion.setOpaque(false);
        presentacion.setLayout(new java.awt.GridBagLayout());

        alumno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alumno.setText("Alumno:   Santiago Gabriel Briceño Fernandez");
        alumno.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 41, 0, 43);
        presentacion.add(alumno, gridBagConstraints);

        profesor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        profesor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profesor.setText("Profesor: Jose Saavedra tirado");
        profesor.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(7, 41, 7, 43);
        presentacion.add(profesor, gridBagConstraints);

        add(presentacion, java.awt.BorderLayout.PAGE_END);

        imagen.setForeground(new java.awt.Color(240, 240, 240));
        imagen.setOpaque(false);
        imagen.setLayout(new java.awt.GridBagLayout());

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoProyecto4.jpeg"))); // NOI18N
        icon.setOpaque(true);
        imagen.add(icon, new java.awt.GridBagConstraints());

        add(imagen, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumno;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel imagen;
    private javax.swing.JLabel materia;
    private javax.swing.JPanel presentacion;
    private javax.swing.JLabel profesor;
    private javax.swing.JPanel titulo;
    private javax.swing.JLabel universidad;
    // End of variables declaration//GEN-END:variables
}
