/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EvaluacionNro1;


/**
 *
 * @author Usuario
 */
public class Ventana1 extends javax.swing.JPanel {

    
    public Ventana1() {
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JPanel();
        universidad = new javax.swing.JLabel();
        materia = new javax.swing.JLabel();
        alumnoProf = new javax.swing.JPanel();
        alumno = new javax.swing.JLabel();
        profesor = new javax.swing.JLabel();
        lateral = new javax.swing.JPanel();
        banderaLateral = new javax.swing.JLabel();
        margen = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        titulo.setOpaque(false);

        universidad.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        universidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        universidad.setText("Universidad José Antonio Paez");

        materia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        materia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        materia.setText("Algoritmos y Estructuras I");

        javax.swing.GroupLayout tituloLayout = new javax.swing.GroupLayout(titulo);
        titulo.setLayout(tituloLayout);
        tituloLayout.setHorizontalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(universidad, javax.swing.GroupLayout.DEFAULT_SIZE, 1011, Short.MAX_VALUE)
            .addComponent(materia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tituloLayout.setVerticalGroup(
            tituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tituloLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(universidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materia)
                .addContainerGap())
        );

        add(titulo, java.awt.BorderLayout.PAGE_START);

        alumnoProf.setOpaque(false);

        alumno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alumno.setText("Alumno:   Santiago Briceño");

        profesor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        profesor.setText("Profesor: José Saavedra Tirado");

        javax.swing.GroupLayout alumnoProfLayout = new javax.swing.GroupLayout(alumnoProf);
        alumnoProf.setLayout(alumnoProfLayout);
        alumnoProfLayout.setHorizontalGroup(
            alumnoProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoProfLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(alumnoProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profesor, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
                    .addComponent(alumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(138, 138, 138))
        );
        alumnoProfLayout.setVerticalGroup(
            alumnoProfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alumnoProfLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(alumno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profesor)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(alumnoProf, java.awt.BorderLayout.PAGE_END);

        lateral.setOpaque(false);

        banderaLateral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UjapProyect1.png"))); // NOI18N

        javax.swing.GroupLayout lateralLayout = new javax.swing.GroupLayout(lateral);
        lateral.setLayout(lateralLayout);
        lateralLayout.setHorizontalGroup(
            lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralLayout.createSequentialGroup()
                .addComponent(banderaLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        lateralLayout.setVerticalGroup(
            lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(banderaLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(lateral, java.awt.BorderLayout.LINE_END);

        margen.setOpaque(false);

        javax.swing.GroupLayout margenLayout = new javax.swing.GroupLayout(margen);
        margen.setLayout(margenLayout);
        margenLayout.setHorizontalGroup(
            margenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        margenLayout.setVerticalGroup(
            margenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );

        add(margen, java.awt.BorderLayout.LINE_START);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoProyecto4.jpeg"))); // NOI18N
        add(logo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alumno;
    private javax.swing.JPanel alumnoProf;
    private javax.swing.JLabel banderaLateral;
    private javax.swing.JPanel lateral;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel margen;
    private javax.swing.JLabel materia;
    private javax.swing.JLabel profesor;
    private javax.swing.JPanel titulo;
    private javax.swing.JLabel universidad;
    // End of variables declaration//GEN-END:variables

    private javax.swing.ImageIcon logoOriginal;
    private javax.swing.Icon logoEscalado;
    
        
   
    
    /*private void cargarImage(JLabel logo){
        logoOriginal = new ImageIcon("/LogoProyecto1.jpg");
        logoEscalado = new ImageIcon(logoOriginal.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH));
        logo.setIcon(logoEscalado);
    }*/

}


