/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EvaluacionNro2;

import javax.swing.JOptionPane;
import static EvaluacionNro2.metodosCalculadoresII.*;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Santiago
 */
public class Ventana1 extends javax.swing.JPanel {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        //iniciarMyN();
        setVisibilidad(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorEnunciado = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enunciado = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        consignas = new javax.swing.JTextArea();
        contenedorIngresos = new javax.swing.JPanel();
        ok = new javax.swing.JButton();
        valorM = new javax.swing.JTextField();
        ingreseM = new javax.swing.JLabel();
        ingreseN = new javax.swing.JLabel();
        valorN = new javax.swing.JTextField();
        reiniciar = new javax.swing.JButton();
        respuesta = new javax.swing.JLabel();
        contenedorRespuesta = new javax.swing.JPanel();
        pregunta1 = new javax.swing.JLabel();
        respuesta5 = new javax.swing.JTextField();
        pregunta2 = new javax.swing.JLabel();
        respuesta4 = new javax.swing.JTextField();
        respuesta2 = new javax.swing.JTextField();
        respuesta1 = new javax.swing.JTextField();
        pregunta5 = new javax.swing.JLabel();
        pregunta3 = new javax.swing.JLabel();
        pregunta4 = new javax.swing.JLabel();
        respuesta3 = new javax.swing.JTextField();
        mostrarNxM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(201, 214, 227));
        setLayout(new java.awt.BorderLayout());

        contenedorEnunciado.setBackground(new java.awt.Color(201, 214, 227));
        contenedorEnunciado.setForeground(new java.awt.Color(201, 214, 227));

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        enunciado.setEditable(false);
        enunciado.setBackground(new java.awt.Color(201, 214, 227));
        enunciado.setColumns(20);
        enunciado.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        enunciado.setRows(5);
        enunciado.setText("Diseñe un programa en Java que al introducir 2\nvalores enteros \"n\" y \"m\" efectue los siguientes calculos:\n1.- evaluar si \"m\" es un número primo\n2.- Mostrar la secuencia de fibonacci hasta\n     el valor menor o igual al resultado de nxm");
        enunciado.setBorder(null);
        jScrollPane1.setViewportView(enunciado);

        jScrollPane3.setBorder(null);

        consignas.setEditable(false);
        consignas.setBackground(new java.awt.Color(201, 214, 227));
        consignas.setColumns(20);
        consignas.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        consignas.setRows(5);
        consignas.setText("3.- Suma de los digitos del resultado NxM\n4.- Factorial de N\n5.- Cantidad de digitos del factorial de N");
        consignas.setBorder(null);
        jScrollPane3.setViewportView(consignas);

        contenedorIngresos.setBackground(new java.awt.Color(201, 214, 227));

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        valorM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorMActionPerformed(evt);
            }
        });

        ingreseM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingreseM.setText("Ingrese un valor para M: ");

        ingreseN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingreseN.setText("Ingrese un valor para N: ");
        ingreseN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        valorN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorNActionPerformed(evt);
            }
        });

        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorIngresosLayout = new javax.swing.GroupLayout(contenedorIngresos);
        contenedorIngresos.setLayout(contenedorIngresosLayout);
        contenedorIngresosLayout.setHorizontalGroup(
            contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingreseN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingreseM, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(valorN)
                    .addComponent(valorM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ok)
                    .addComponent(reiniciar))
                .addContainerGap())
        );
        contenedorIngresosLayout.setVerticalGroup(
            contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorIngresosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok))
                .addGap(4, 4, 4)
                .addGroup(contenedorIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reiniciar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        respuesta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        respuesta.setText("RESPUESTAS");

        javax.swing.GroupLayout contenedorEnunciadoLayout = new javax.swing.GroupLayout(contenedorEnunciado);
        contenedorEnunciado.setLayout(contenedorEnunciadoLayout);
        contenedorEnunciadoLayout.setHorizontalGroup(
            contenedorEnunciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorEnunciadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(contenedorEnunciadoLayout.createSequentialGroup()
                .addComponent(contenedorIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 322, Short.MAX_VALUE))
        );
        contenedorEnunciadoLayout.setVerticalGroup(
            contenedorEnunciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorEnunciadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorEnunciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(contenedorEnunciadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorEnunciadoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contenedorEnunciadoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(respuesta)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        add(contenedorEnunciado, java.awt.BorderLayout.PAGE_START);

        contenedorRespuesta.setBackground(new java.awt.Color(201, 214, 227));

        pregunta1.setText("R1.- M es primo: ");

        pregunta2.setText("R2.- La secuencia de fibonacci resultante es: ");

        respuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta4ActionPerformed(evt);
            }
        });

        respuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta2ActionPerformed(evt);
            }
        });

        respuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuesta1ActionPerformed(evt);
            }
        });

        pregunta5.setText("R5.- El factorial de N tiene un total de: ");

        pregunta3.setText("R3.- Los digitos de NxM suman un total de: ");

        pregunta4.setText("R4.- Factorial de N: ");

        mostrarNxM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarNxMActionPerformed(evt);
            }
        });

        jLabel1.setText("N x M : ");

        javax.swing.GroupLayout contenedorRespuestaLayout = new javax.swing.GroupLayout(contenedorRespuesta);
        contenedorRespuesta.setLayout(contenedorRespuestaLayout);
        contenedorRespuestaLayout.setHorizontalGroup(
            contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorRespuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorRespuestaLayout.createSequentialGroup()
                        .addComponent(pregunta5)
                        .addGap(18, 18, 18)
                        .addComponent(respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(contenedorRespuestaLayout.createSequentialGroup()
                        .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pregunta4)
                            .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenedorRespuestaLayout.createSequentialGroup()
                                    .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(contenedorRespuestaLayout.createSequentialGroup()
                                            .addComponent(pregunta1)
                                            .addGap(18, 18, 18)
                                            .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(pregunta2)
                                        .addComponent(pregunta3))
                                    .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(contenedorRespuestaLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenedorRespuestaLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(respuesta2))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenedorRespuestaLayout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mostrarNxM, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(248, Short.MAX_VALUE))))
        );
        contenedorRespuestaLayout.setVerticalGroup(
            contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorRespuestaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta1)
                    .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarNxM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta2)
                    .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta3)
                    .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta4)
                    .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorRespuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta5)
                    .addComponent(respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        add(contenedorRespuesta, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void valorNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorNActionPerformed

    private void valorMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        
        if(!verificarIngreso()){
            calculosPertinentes();
        }

// TODO add your handling code here:
    }//GEN-LAST:event_okActionPerformed

    private void iniciarMyN(){
        valorN.setText((int) (Math.random() * 99) + "");
        valorM.setText((int) (Math.random() * 99) + "");
    }
    
    private boolean verificarIngreso(){
        boolean noIngreso = false, numeroInvalido = false;
        if((valorN.getText().equals("") || valorM.getText().equals(""))){
            noIngreso = true;
            //JOptionPane.showMessageDialog(pregunta1, "Ingrese los valores solicitados");
            if(ingresoNumeroValido(valorN.getText()) == false || ingresoNumeroValido(valorM.getText()) == false){
                numeroInvalido = true;
            }           
        }
        
        if(noIngreso && numeroInvalido){
            JOptionPane.showMessageDialog(pregunta1, "Ingrese los valores solicitados en el formato solicitado");
            valorN.setText("");
            valorM.setText("");
        }else if(noIngreso && !numeroInvalido){
            JOptionPane.showMessageDialog(pregunta1, "Ingrese los valores solicitados");
        }else if(!noIngreso && numeroInvalido){
            JOptionPane.showMessageDialog(pregunta1, "Ingrese valores enteros entre 0 y 9");
            valorN.setText("");
            valorM.setText("");
        }
        
        return numeroInvalido && noIngreso;
    }
    
    private boolean ingresoNumeroValido(String txt) {
        boolean valido;
        if(txt.equals("")){
            valido = false;
        } else {
            valido = txt.matches("[0-9]");
        }
        return valido;
        

    }
    
    private void calculosPertinentes(){
        
        respuesta.setVisible(true);
        int m = parseInt(valorM.getText()), n = parseInt(valorN.getText());
        int nM = n*m;
        
        respuesta1.setText(esPrimo(m) + "");
        respuesta2.setText(fibonacciHasta(nM));
        respuesta3.setText(sumaDeDigitos(nM) + "");
        respuesta4.setText(factorial(n) + "");
        respuesta5.setText(numeroCifras(factorial(n))+"");
        mostrarNxM.setText(nM + "");
        contenedorRespuesta.setVisible(true);
        ok.setEnabled(false);
        reiniciar.setEnabled(true);
        
    }
    
    private void setVisibilidad(boolean visible){
        respuesta.setVisible(visible);
        contenedorRespuesta.setVisible(visible);
        reiniciar.setEnabled(visible);
        
        
        
    
    }
    
    
    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        setVisibilidad(true);
        reinicia();
        //iniciarMyN();
    }//GEN-LAST:event_reiniciarActionPerformed

    private void reinicia(){
        respuesta1.setText("");
        respuesta2.setText("");
        respuesta3.setText("");
        respuesta4.setText("");
        respuesta5.setText("");
        mostrarNxM.setText("");
        valorN.setText("");
        valorM.setText("");
        ok.setEnabled(true);
        setVisibilidad(false);
        
        
    }
    
    private void mostrarNxMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarNxMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarNxMActionPerformed

    private void respuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta1ActionPerformed

    private void respuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta2ActionPerformed

    private void respuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuesta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta4ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consignas;
    private javax.swing.JPanel contenedorEnunciado;
    private javax.swing.JPanel contenedorIngresos;
    private javax.swing.JPanel contenedorRespuesta;
    private javax.swing.JTextArea enunciado;
    private javax.swing.JLabel ingreseM;
    private javax.swing.JLabel ingreseN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField mostrarNxM;
    private javax.swing.JButton ok;
    private javax.swing.JLabel pregunta1;
    private javax.swing.JLabel pregunta2;
    private javax.swing.JLabel pregunta3;
    private javax.swing.JLabel pregunta4;
    private javax.swing.JLabel pregunta5;
    private javax.swing.JButton reiniciar;
    private javax.swing.JLabel respuesta;
    private javax.swing.JTextField respuesta1;
    private javax.swing.JTextField respuesta2;
    private javax.swing.JTextField respuesta3;
    private javax.swing.JTextField respuesta4;
    private javax.swing.JTextField respuesta5;
    private javax.swing.JTextField valorM;
    private javax.swing.JTextField valorN;
    // End of variables declaration//GEN-END:variables

    



}
